# Generated by Django 5.1.2 on 2024-11-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('scenario', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('choice_a', models.TextField()),
                ('choice_a_type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=20)),
                ('choice_b', models.TextField()),
                ('choice_b_type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('A', 'Choice A'), ('B', 'Choice B')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
